[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
src = ["src"]
select = ["I001", "F401"]

[tool.ruff.isort]
known-first-party = ["src"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true
